import { Cat } from './cat';

export const CATEGORIES: Cat[] = [
  { id: 0, name: 'Alle Kategorien', class: "" },   
  { id: 6018, name: 'Bücher', class: "cat-books" },
  { id: 6014, name: 'Spiele', class: "cat-games" }, 
  { id: 6007, name: 'Produktivität', class: "cat-prod" },
  { id: 6008, name: 'Foto und Video', class: "cat-photo" },
  { id: 6003, name: 'Reisen', class: "cat-travel" },
  { id: 6004, name: 'Sport', class: "cat-sport" },
  { id: 6016, name: 'Unterhaltung', class: "cat-entertain" },
  { id: 6000, name: 'Wirtschaft', class: "cat-business" },
  { id: 6002, name: 'Dienstprogramme', class: "cat-utilities" }, 
  //{ id: 6009, name: 'Nachrichten', class: "cat-news" },
  //{ id: 6025, name: 'Sticker', class: "cat-sticker" },
  //{ id: 6024, name: 'Shopping', class: "cat-shop" },
  { id: 6010, name: 'Navigation', class: "cat-nav" },
  { id: 6011, name: 'Musik', class: "cat-music" },  
  { id: 6012, name: 'Lifestyle', class: "cat-lifestyle" },
  { id: 6013, name: 'Gesundheit und Fitness', class: "cat-health" },
  { id: 6005, name: 'Soziale Netze', class: "cat-social" },  
  { id: 6006, name: 'Nachschlagewerke', class: "cat-ref" },
  { id: 6015, name: 'Finanzen', class: "cat-finance" },  
  { id: 6017, name: 'Bildung', class: "cat-edu" },
  { id: 6001, name: 'Wetter', class: "cat-weather" },  
  { id: 6020, name: 'Medizin', class: "cat-medical" },
  { id: 6021, name: 'Zeitungen und Zeitschriften', class: "cat-magazine" },
  { id: 6022, name: 'Kataloge', class: "cat-catalogue" },
  { id: 6023, name: 'Essen und Trinken', class: "cat-food" },
  { id: 12001, name: 'Wirtschaft', class: "" },  
  { id: 12002, name: 'Entwickler-Tools', class: "" },
  { id: 12003, name: 'Bildung', class: "" },
  { id: 12004, name: 'Unterhaltung', class: "" },
  { id: 12005, name: 'Finanzen', class: "" },
  { id: 12006, name: 'Spiele', class: "" },
  { id: 12022, name: 'Grafik und Design', class: "" },
  { id: 12007, name: 'Gesundheit und Fitness', class: "" },
  { id: 12008, name: 'Lifestyle', class: "" },  
  { id: 12010, name: 'Medizin', class: "" },
  { id: 12011, name: 'Musik', class: "" },
  { id: 12012, name: 'Nachrichten', class: "" },
  { id: 12013, name: 'Fotografie', class: "" },
  { id: 12014, name: 'Produktivität', class: "" },
  { id: 12015, name: 'Nachschlagewerke', class: "" },
  { id: 12016, name: 'Soziale Netze', class: "" },
  { id: 12017, name: 'Sport', class: "" },
  { id: 12018, name: 'Reisen', class: "" },
  { id: 12019, name: 'Dienstprogramme', class: "" },
  { id: 12020, name: 'Video', class: "" },
  { id: 12021, name: 'Wetter', class: "" },
  ];

export const SUBCATEGORIES: Cat[] = [
  { id: 0, name: 'Alle', class: "" },
  { id:7001, name:"Action", class: "" },
  {id:7002, name:"Abenteuer", class: "" },
  {id:7003, name:"Spielhalle", class: "" },
  {id:7004, name:"Brettspiele", class: "" },
  {id:7005, name:"Kartenspiele", class: "" },
  {id:7006, name:"Casino", class: "" },
  {id:7007, name:"Würfelspiele", class: "" },
  {id:7008, name:"Bildung", class: "" },
  {id:7009, name:"Familie", class: "" },
  {id:7010, name:"Kinder", class: "" }, 
  {id:7011, name:"Musik", class: "" },
  {id:7012, name:"Puzzle", class: "" },
  {id:7013, name:"Rennsport", class: "" },
  {id:7014, name:"Rollenspiel", class: "" },
  {id:7015, name:"Simulation", class: "" },
  {id:7016, name:"Sport", class: "" },
  {id:7017, name:"Strategie", class: "" },
  {id:7018, name:"Quiz- und Denkspiele", class: "" },
  {id:7019, name:"Wortspiele", class: "" },
  {id:12201, name:"Action", class: "" },
  {id:12202, name:"Abenteuer", class: "" },
  {id:12203, name:"Arcade-Spiele", class: "" },
  {id:12204, name:"Brettspiele", class: "" },
  {id:12205, name:"Kartenspiele", class: "" },
  {id:12206, name:"Casino", class: "" },
  {id:12207, name:"Würfelspiele", class: "" },
  {id:12208, name:"Bildung", class: "" },
  {id:12209, name:"Familie", class: "" },
  {id:12210, name:"Kinder", class: "" },
  {id:12211, name:"Musik", class: "" },
  {id:12212, name:"Puzzle", class: "" },
  {id:12213, name:"Rennsport", class: "" },
  {id:12214, name:"Rollenspiel", class: "" },
  {id:12215, name:"Simulation", class: "" },
  {id:12216, name:"Sport", class: "" },
  {id:12217, name:"Strategie", class: "" },
  {id:12218, name:"Quiz- und Denkspiele", class: "" },
  {id:12219, name:"Wortspiele", class: "" } 
];